[AC-5619] Add React
masschallenge/application-allocator pull request #2
Opened 2018-05-21 19:17 UTC by mc-nathan

To test:
- Run `make run-server`

Should startup a webserver and give you a local URL you can checkout out.  The local URL should just say "HELLO".

2018-05-24 16:07 UTC, jonkiparsky requested changes
yarn.lock is a generated file, should it really be committed to the repo?

2018-05-24 16:07 UTC, jonkiparsky commented on Makefile
> +	@brew install node
homebrew is a mac-specific installer. Is this really the best way to do this?

2018-05-24 16:07 UTC, jonkiparsky commented on bin/setup
> +  printf "💀${RED}   You must install node on your system before setup can continue${NO_COLOR}\n"
Do we really need the emojis and color?

2018-05-24 16:07 UTC, jonkiparsky commented on Makefile
> +	@brew install node
Also, this setup configuration conflicted with an existing install of node, I had to do a bunch of manual deletion and permissions twiddling to resolve it. We should probably try to make that safe.

2018-06-04 21:05 UTC, mc-nathan commented
Yes, yarn.lock should be checked in.  It is a record of the resolution of the version closure that has been installed and presumably tested.  This is the file that should determine which versions actually get installed on production.  This is similar to the standard we want to get to in Python, pyenv, and Ruby's bundler.

2018-06-04 21:06 UTC, mc-nathan commented on bin/setup
> +  printf "💀${RED}   You must install node on your system before setup can continue${NO_COLOR}\n"
This was a script from thoughtbot and it is essentially the same as the one on in the directory repo.  We should find a way to share it, but I don't think we should edit it on this PR.

2018-06-04 21:26 UTC, mc-nathan commented on Makefile
> +	@brew install node
OK, I think I made things safer.  A bit tricky to test without starting from a clean box, but it definite avoids messing with any existing version of node or yarn.  Ultimately this should all get handed by the docker stuff, but we haven't gotten there yet.

2018-06-04 21:27 UTC, mc-nathan commented on bin/setup
> +  printf "💀${RED}   You must install node on your system before setup can continue${NO_COLOR}\n"
Ended up not needing with the clean up to the Makefile do I deleted it.

2018-06-05 17:49 UTC, jonkiparsky commented
Is this error expected? 
<img width="314" alt="screen shot 2018-06-05 at 1 47 42 pm" src="https://user-images.githubusercontent.com/5283553/40993283-2a119b96-68c7-11e8-992a-f44dbe35e7e4.png">

2018-06-05 17:49 UTC, jonkiparsky requested changes
When I load, I see the hello world text, but also "Error: failed to fetch"
I assume this error is not expected?

2018-06-11 18:14 UTC, jonkiparsky commented
Closing per discussion with @mc-nathan

2018-06-11 18:14 UTC, closed without merging